services:
    server:
        build:
            context: ./apps/server
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        volumes:
            - ./apps/server:/app
            - ./node_modules:/app/node_modules
        environment:
            - NODE_ENV=development
